/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parkir;
import com.mysql.jdbc.Statement;
import javax.swing.JOptionPane;
import connection.koneksi;
import java.util.Stack;
/**
 *
 * @author user
 */
public class ProgramParkir extends javax.swing.JFrame {
    Stack result = new Stack();
    public ProgramParkir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        noKendaraan = new javax.swing.JTextField();
        hargaParkir = new javax.swing.JTextField();
        jamMasuk = new javax.swing.JTextField();
        lamaParkir = new javax.swing.JTextField();
        totalBayar = new javax.swing.JTextField();
        motor = new javax.swing.JRadioButton();
        mobil = new javax.swing.JRadioButton();
        btnProses = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnSave = new javax.swing.JToggleButton();
        jLabel10 = new javax.swing.JLabel();

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parkir/guiparkir.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("PROGRAM PEMBAYARAN PARKIR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 13, -1, -1));

        jLabel2.setText("No. Kendaraan");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 57, -1, -1));

        jLabel3.setText("Jenis Kendaraan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 98, -1, -1));

        jLabel4.setText("Harga Parkir");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 140, -1, -1));

        jLabel5.setText("Jam Masuk");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 180, -1, -1));

        jLabel6.setText("Lama Parkir");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 220, -1, -1));

        jLabel7.setText("Total Bayar");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 317, -1, -1));

        jLabel8.setText("Jam");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 220, -1, -1));
        getContentPane().add(noKendaraan, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 54, 95, -1));
        getContentPane().add(hargaParkir, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 137, 95, -1));
        getContentPane().add(jamMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 177, 95, -1));
        getContentPane().add(lamaParkir, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 217, 95, -1));
        getContentPane().add(totalBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 314, 95, -1));

        motor.setText("Motor");
        motor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motorActionPerformed(evt);
            }
        });
        getContentPane().add(motor, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 94, -1, -1));

        mobil.setText("Mobil");
        mobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobilActionPerformed(evt);
            }
        });
        getContentPane().add(mobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 94, -1, -1));

        btnProses.setText("PROSES");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });
        getContentPane().add(btnProses, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 271, -1, -1));

        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        btnClose.setText("CLOSE");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));

        btnSave.setText("SHOW");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 70, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parkir/guiparkir.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void motorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motorActionPerformed
       hargaParkir.setText("2000");
       jamMasuk.setText("");
    }//GEN-LAST:event_motorActionPerformed

    private void mobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobilActionPerformed
       hargaParkir.setText("5000");
       jamMasuk.setText("");
    }//GEN-LAST:event_mobilActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        int d = Integer.parseInt(hargaParkir.getText());
        int harga = Integer.parseInt(lamaParkir.getText());
        int hasilnya = harga*d;
        totalBayar.setText("" + hasilnya);
    }//GEN-LAST:event_btnProsesActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed

        String NoPol = noKendaraan.getText();
        String Bayar = hargaParkir.getText();
        String Jam = jamMasuk.getText();
        String Durasi = lamaParkir.getText();
        String Total = totalBayar.getText();
        result.push(Total);

        try{
            int harga = Integer.parseInt(hargaParkir.getText());
            if (harga == 2000){
            Statement statement = (Statement) koneksi.GetConnection().createStatement();
            statement.executeUpdate("Insert into basement VALUES ('" +NoPol+ "','" +"Motor"+ "','" +Bayar+ "' ,'" +Jam+ "' ,'" +Durasi+ "','" +Total+ "');");
            statement.close();
            JOptionPane.showMessageDialog(null, "data berhasil disimpan");
            }
            else{
            Statement statement = (Statement) koneksi.GetConnection().createStatement();
            statement.executeUpdate("Insert into basement VALUES ('" +NoPol+ "','" +"Mobil"+ "','" +Bayar+ "' ,'" +Jam+ "' ,'" +Durasi+ "','" +Total+ "');");
            statement.close();
            JOptionPane.showMessageDialog(null, "data berhasil disimpan");
            }
        }catch(Exception t)
        {
            JOptionPane.showMessageDialog(null, "data gagal disimpan");
        }
        noKendaraan.setText("");
        jamMasuk.setText("");
        lamaParkir.setText("");
        hargaParkir.setText("");
        totalBayar.setText("");
        motor.setSelected (false);
        mobil.setSelected (false);
        motor.setEnabled (true);
        mobil.setEnabled (true); 
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        int jawab = JOptionPane.showConfirmDialog(this, "Apakah anda ingin keluar?");
        
        switch (jawab){
            case JOptionPane.YES_OPTION:
            JOptionPane.showMessageDialog(this, "OK");
            System.exit(0);
            break;
            case JOptionPane.NO_OPTION:
                JOptionPane.showMessageDialog(this, "Silahkan Lanjut");
                break;    
        }
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

       {
        JOptionPane.showMessageDialog(this, result, "Data masuk hari ini", JOptionPane.PLAIN_MESSAGE);
    }
            // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgramParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgramParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgramParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgramParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgramParkir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnProses;
    private javax.swing.JToggleButton btnSave;
    private javax.swing.JTextField hargaParkir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jamMasuk;
    private javax.swing.JTextField lamaParkir;
    private javax.swing.JRadioButton mobil;
    private javax.swing.JRadioButton motor;
    private javax.swing.JTextField noKendaraan;
    private javax.swing.JTextField totalBayar;
    // End of variables declaration//GEN-END:variables
}
